#!/usr/bin/env sh

# relative navigation shortcuts
alias .='echo $PWD'

# clear the screen and scrollback buffer
alias cls='printf "\33c\e[3J"'

# use interactive mode as a safeguard
alias cp='cp -i'
alias ln='ln -i'
alias mv='mv -i'
alias rm='rm -i'

# list only non-hidden entries
alias ll='ls -lhF'

# list only hidden (dotfile) entries
alias l.='ls -dF .*'
alias ls.='ls -dF .*'
alias ll.='ls -lhdF .*'

# list only sub-directory entries
alias lsd='ls -ldeh */'

# list all entries
alias lla='ls -alhF'

# list all entries, include ACL attributes
alias lle='ls -alheF'

# sort listing by size
alias llS='ls -alheFS'

# display complete time stamps
alias llT='ls -alheFT'

# grep the directory listing, ignore-case
alias llg='ls -alheF | grep -i'

# paginate listing
alias lll='ls -alheF | less -M'
alias llm='ls -alheF | most'

# always long list the directory stack
alias dirs='dirs -v'

# long list the stack after pop
alias popd='popd &> /dev/null; dirs -v'

# supress stack list after push
alias pushd='pushd > /dev/null'

# Long lists the active jobs in the current shell
alias jobs='jobs -l'

# create parent directories as needed
alias mkdir='mkdir -pv'

# pretty print PATH variable
alias path='echo -e ${PATH//:/\\n}'

# grep processes, ignore-case
alias psg='ps aux | grep -i'

# only show one level by default when running tree command
alias tree='tree -L 1'

# fix unintuitive unix command names
alias unmount='umount'

# output random hexidecimal gradoo
alias gradoo='cat /dev/urandom | hexdump -C | grep "ca fe"'

# Git
alias amend='git commit --amend'
alias branch='git checkout -b'
alias branches='git branch --all'
alias checkout='git checkout'
alias commit='git commit'
alias rebase='git rebase'
alias remotes='git remote --verbose'
alias stage='git add'
alias stash='git stash'
alias status='git status'
alias switch='git switch'
alias unstage='git reset HEAD'

# Git Large File Storage
alias lfs='git lfs'

# extend git with GitHub commands
alias git='hub'

# Kitty terminal emulator
alias icat='kitty +kitten icat'
alias kdiff='kitty +kitten diff'

# OpenSSL checksums
alias digest='/usr/bin/openssl dgst'

# Python
alias py='python'
alias py3='python3'

# SQLite
alias sqlite='sqlite3'

### macOS specific

# Google Chrome
# work around for XHR issues in Chrome when working locally
alias chrome='open -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --allow-file-access-from-files'

# Delete .DS_Store files recursively from execution directory
alias delete_ds_store="sudo find . -type f -name '.DS_Store' -ls -delete"

# flush directory service and local DNS cache
alias resetDNS='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder && echo "macOS DNS Cache Reset"'

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

# Preview
alias preview='open -a /Applications/Preview.app'

# Safari
alias safari='open -a /Applications/Safari.app'

# Terminal-notifier
alias notify='/usr/local/bin/terminal-notifier'

# Quick Look (^C or space to close)
alias qlp='qlmanage -p 2>/dev/null'
alias qlr='qlmanage -r cache'

# webkit2png
alias w2p='/usr/local/bin/webkit2png'
