#!/usr/bin/env zsh
#
# Zsh shell environment configuration
#
# This file is automatically loaded for every new session,
# configurtion file load order:
# .zshenv → [.zprofile if login] → [.zshrc if interactive] → [.zlogin if login]
#

# Disable Loading Global Profiles
# macOS (>= 10.11) loads /etc/zprofile after user ~/.zshenv is loaded
# /etc/zprofile calls /usr/libexec/path_helper, which adds system directories
# to $PATH, reorders it, and then removes duplicates.
setopt no_global_rcs
