#!/usr/bin/env sh

# relative navigation shortcuts
alias .='echo $PWD'

# clear the screen and scrollback buffer
alias cls='printf "\33c\e[3J"'

# use interactive mode as a safeguard
alias cp='cp -i'
alias ln='ln -i'
alias mv='mv -i'
alias rm='rm -i'

if command -v eza > /dev/null ; then
  # replace built-in ls command with eza called with options:
  alias ls='eza --colour-scale=size --hyperlink --icons --no-quotes'

  # display long list of entries
  alias ll='ls --long --header --total-size'

  # include dot file entries
  alias lla='ls --long --header --all --all'

  # grep list of entries, ignore-case
  alias llg='ls --long --header -all | grep -i'

  # display numeric user and group ids
  alias lln='ll --all --numeric'

  # display permission in octal format
  alias ll8='ll --all --octal-permissions'

  # list only directory entries
  alias lsd='ls --only-dirs --show-symlinks --total-size'
  alias lld='ll --only-dirs --show-symlinks --total-size'

  # list only file entries
  alias lsf='ls --only-files --show-symlinks'
  alias llf='ll --only-files --show-symlinks'

  # list entries by last creation date
  alias llc='ll --sort=created'

  # list entries by last modified date
  alias llm='ll --sort=oldest'

  # list entries by last modified date
  alias llr='ll --time-style=relative'

  # list entries by list entries by  by size, decending
  alias lls='ll --reverse --sort=size'

  # list entries by file type
  alias llt='ll --sort=type'

  alias tree='ls --tree --level=2 --group-directories-first'

else
  # list all entries
  alias ll='ls -lhF'

  # include dot file entries
  alias lla='ls -alhF'

  # grep list of entries, ignore-case
  alias llg='ls -alheF | grep -i'

  # list only directory entries
  alias lsd='ls -deh */'
  alias lld='ls -ldeh */'

  # list entries by size
  alias lls='ls -lheFS'
fi

# use long list format for dirs stack
alias dirs='dirs -v'

# list the dirs stack after pop
alias popd='popd &> /dev/null; dirs -v'

# supress stack list after push
alias pushd='pushd > /dev/null'

# use long format for list of active jobs in the current shell
alias jobs='jobs -l'

# akways create parent directories as needed
alias mkdir='mkdir -pv'

# pretty print PATH variable
alias path='echo -e ${PATH//:/\\n}'

# grep processes, ignore-case
alias psg='ps aux | grep -i'

# fix unintuitive unix command names
alias unmount='umount'

# output random hexidecimal gradoo
alias gradoo='cat /dev/urandom | hexdump -C | grep "ca fe"'

# Git
alias amend='git commit --amend'
alias branch='git checkout -b'
alias branches='git branch --all'
alias checkout='git checkout'
alias commit='git commit'
alias rebase='git rebase'
alias remotes='git remote --verbose'
alias stage='git add'
alias stash='git stash'
alias status='git status'
alias switch='git switch'
alias unstage='git reset HEAD'

# Git Large File Storage
alias lfs='git lfs'

# OpenSSL checksums
alias digest='/usr/bin/openssl dgst'

# Kamal https://kamal-deploy.org/docs/installation/
alias kamal='docker run -it --rm -v "${PWD}:/workdir" -v "/run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock" -e SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock" -v /var/run/docker.sock:/var/run/docker.sock ghcr.io/basecamp/kamal:latest'

### macOS specific

# Google Chrome
# work around for XHR issues in Chrome when working locally
alias chrome='open -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --allow-file-access-from-files'

# Delete .DS_Store files recursively from execution directory
alias delete_ds_store="sudo find . -type f -name '.DS_Store' -ls -delete"

# flush directory service and local DNS cache
alias resetDNS='sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder && echo "macOS DNS Cache Reset"'

# Merge PDF files
# Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/MacOS/join'

# Preview
alias preview='open -a /Applications/Preview.app'

# Safari
alias safari='open -a /Applications/Safari.app'

# Terminal-notifier
alias notify='/usr/local/bin/terminal-notifier'

# Quick Look (^C or space to close)
alias qlp='qlmanage -p 2>/dev/null'
alias qlr='qlmanage -r cache'

