#!/usr/bin/env zsh
#
# [Spaceship ZSH](https://denysdovhan.com/spaceship-prompt/)
#
SPACESHIP_PROMPT_ORDER=(
  user
  host
  dir
  git
  jobs
  ruby
  pyenv
  venv
  node
  line_sep
  #vi_mode
  char
)

SPACESHIP_RPROMPT_ORDER=(
)

SPACESHIP_USER_PREFIX=''
SPACESHIP_USER_SHOW='always'
SPACESHIP_USER_COLOR='green'
SPACESHIP_USER_COLOR_ROOT='red'

SPACESHIP_HOST_SHOW='always'
SPACESHIP_HOST_COLOR='blue'
SPACESHIP_HOST_COLOR_SSH='green'

SPACESHIP_DIR_SHOW='always'
SPACESHIP_DIR_COLOR='cyan'
SPACESHIP_DIR_LOCK_COLOR='red'
SPACESHIP_DIR_LOCK_SYMBOL=''
SPACESHIP_DIR_TRUNC=3
SPACESHIP_DIR_TRUNC_PREFIX='…/'
SPACESHIP_DIR_TRUNC_REPO=true

SPACESHIP_GIT_SYMBOL=''
SPACESHIP_GIT_BRANCH_PREFIX=''
SPACESHIP_GIT_BRANCH_COLOR='magenta'
SPACESHIP_GIT_STATUS_COLOR='magenta'
SPACESHIP_GIT_STATUS_PREFIX=' '
SPACESHIP_GIT_STATUS_SUFFIX=''
SPACESHIP_GIT_STATUS_UNTRACKED='?'  # alt '✭'
SPACESHIP_GIT_STATUS_ADDED='+'      # alt '✚' or '+'
SPACESHIP_GIT_STATUS_MODIFIED='⦿'   # alt '✹' or '☉' or '⦿' or '✻' or '∗'
SPACESHIP_GIT_STATUS_RENAMED='↳'    # alt '➜' or '⤞' or '⇥' or '↳'
SPACESHIP_GIT_STATUS_DELETED='!'    # alt '✖' or '!' or '⊖' or '⤼'
SPACESHIP_GIT_STATUS_STASHED='❖'    # alt '❖' or '✭'
SPACESHIP_GIT_STATUS_UNMERGED='⚠'   # alt '⚠' or '⊄' or '≠' or '≉'
SPACESHIP_GIT_STATUS_AHEAD='⇡'      # alt '⤒' or '⇡'
SPACESHIP_GIT_STATUS_BEHIND='⇣'     # alt '⤓' or '⇣'
SPACESHIP_GIT_STATUS_DIVERGED='⇡⇣'  # alt '∓' or '⇡⇣' or '≠' or '≉' or '±'

SPACESHIP_JOBS_SYMBOL='✦'
SPACESHIP_JOBS_COLOR='blue'

SPACESHIP_PYENV_PREFIX=' '
SPACESHIP_PYENV_SUFFIX=''
SPACESHIP_PYENV_SYMBOL='Python '

SPACESHIP_VENV_PREFIX='('
SPACESHIP_VENV_SUFFIX=')'
SPACESHIP_VENV_SYMBOL='venv:'

SPACESHIP_RUBY_PREFIX=' '
SPACESHIP_RUBY_SUFFIX=''
SPACESHIP_RUBY_SYMBOL='Ruby '

SPACESHIP_NODE_PREFIX=' '
SPACESHIP_NODE_SUFFIX=''
SPACESHIP_NODE_SYMBOL='Node '

SPACESHIP_VI_MODE_COLOR='white'
SPACESHIP_VI_MODE_INSERT='[I]'
SPACESHIP_VI_MODE_NORMAL='[N]'

SPACESHIP_CHAR_PREFIX=''
SPACESHIP_CHAR_SUFFIX=' '
SPACESHIP_CHAR_SYMBOL='❯'       # alt '→' or '➔'
SPACESHIP_CHAR_SYMBOL_ROOT='☛' # alt '' or '➤' or '⚡'
SPACESHIP_CHAR_SYMBOL_SECONDARY='↪ '
