#!/usr/bin/env zsh
#
# [Spaceship ZSH](https://denysdovhan.com/spaceship-prompt/)
#
SPACESHIP_PROMPT_ORDER=(
  user
  host
  dir
  git
  jobs
  ruby
  pyenv
  venv
  node
  line_sep
  #vi_mode
  char
)

SPACESHIP_RPROMPT_ORDER=(
)

SPACESHIP_USER_PREFIX=''
SPACESHIP_USER_SHOW='always'
SPACESHIP_USER_COLOR='green'
SPACESHIP_USER_COLOR_ROOT='red'

SPACESHIP_HOST_SHOW='always'
SPACESHIP_HOST_COLOR='blue'
SPACESHIP_HOST_COLOR_SSH='green'

SPACESHIP_DIR_SHOW='always'
SPACESHIP_DIR_COLOR='cyan'
SPACESHIP_DIR_TRUNC=4
SPACESHIP_DIR_TRUNC_PREFIX='…/'
SPACESHIP_DIR_TRUNC_REPO=true

SPACESHIP_GIT_SYMBOL=''
SPACESHIP_GIT_BRANCH_PREFIX=''
SPACESHIP_GIT_BRANCH_COLOR='magenta'
SPACESHIP_GIT_STATUS_COLOR='magenta'
SPACESHIP_GIT_STATUS_PREFIX=' '
SPACESHIP_GIT_STATUS_SUFFIX=''
SPACESHIP_GIT_STATUS_UNTRACKED='?'
SPACESHIP_GIT_STATUS_ADDED='+'
SPACESHIP_GIT_STATUS_MODIFIED='✻'
SPACESHIP_GIT_STATUS_RENAMED='⤞'
SPACESHIP_GIT_STATUS_DELETED='!'
SPACESHIP_GIT_STATUS_STASHED='❖'
SPACESHIP_GIT_STATUS_UNMERGED='⚠'
SPACESHIP_GIT_STATUS_AHEAD='⇡'
SPACESHIP_GIT_STATUS_BEHIND='⇣'
SPACESHIP_GIT_STATUS_DIVERGED='⇡⇣'

SPACESHIP_JOBS_SYMBOL='✦'
SPACESHIP_JOBS_COLOR='blue'

SPACESHIP_PYENV_PREFIX='Python '
SPACESHIP_PYENV_SYMBOL=''
SPACESHIP_VENV_PREFIX=''

SPACESHIP_RUBY_PREFIX='Ruby '
SPACESHIP_RUBY_SYMBOL=''

SPACESHIP_NODE_PREFIX='Node '
SPACESHIP_NODE_SYMBOL=''

SPACESHIP_VI_MODE_COLOR='white'
SPACESHIP_VI_MODE_INSERT='[I]'
SPACESHIP_VI_MODE_NORMAL='[N]'

SPACESHIP_CHAR_PREFIX=''
SPACESHIP_CHAR_SYMBOL='→'
SPACESHIP_CHAR_SYMBOL_SECONDARY='↪ '
SPACESHIP_CHAR_SYMBOL_ROOT='☛'
SPACESHIP_CHAR_SUFFIX=' '
