#!/usr/bin/env zsh
#
# Spaceship ZSH
# https://denysdovhan.com/spaceship-prompt/
#
SPACESHIP_PROMPT_ORDER=(
  user
  host
  dir
  git
  jobs
  ruby
  pyenv
  venv
  node
  line_sep
  #vi_mode
  char
)

SPACESHIP_RPROMPT_ORDER=(
)

SPACESHIP_USER_PREFIX=''
SPACESHIP_USER_SHOW='always'
SPACESHIP_USER_COLOR='white'
SPACESHIP_USER_COLOR_ROOT='red'

SPACESHIP_HOST_COLOR='white'
SPACESHIP_HOST_COLOR_SSH='white'

SPACESHIP_DIR_COLOR='cyan'
SPACESHIP_DIR_LOCK_COLOR='red'
SPACESHIP_DIR_LOCK_SYMBOL=''
SPACESHIP_DIR_TRUNC=3
SPACESHIP_DIR_TRUNC_PREFIX='.../'
SPACESHIP_DIR_TRUNC_REPO=true

SPACESHIP_GIT_BRANCH_COLOR='magenta'
SPACESHIP_GIT_SYMBOL=''
SPACESHIP_GIT_BRANCH_PREFIX=''
SPACESHIP_GIT_STATUS_COLOR='magenta'
SPACESHIP_GIT_STATUS_PREFIX=' '
SPACESHIP_GIT_STATUS_SUFFIX=''
SPACESHIP_GIT_STATUS_UNTRACKED='?'
SPACESHIP_GIT_STATUS_ADDED='+'
SPACESHIP_GIT_STATUS_MODIFIED='⦿'
SPACESHIP_GIT_STATUS_RENAMED='➜'
SPACESHIP_GIT_STATUS_DELETED='!'
SPACESHIP_GIT_STATUS_STASHED='❖'
SPACESHIP_GIT_STATUS_UNMERGED='⚠'
SPACESHIP_GIT_STATUS_AHEAD='⇡'
SPACESHIP_GIT_STATUS_BEHIND='⇣'
SPACESHIP_GIT_STATUS_DIVERGED='⇡⇣'

SPACESHIP_JOBS_COLOR='blue'
SPACESHIP_JOBS_SYMBOL='✦'

SPACESHIP_PYENV_PREFIX=' '
SPACESHIP_PYENV_SUFFIX=''
SPACESHIP_PYENV_COLOR='yellow'
SPACESHIP_PYENV_SYMBOL='Python '

SPACESHIP_VENV_PREFIX='('
SPACESHIP_VENV_SUFFIX=')'
SPACESHIP_VENV_COLOR='yellow'
SPACESHIP_VENV_SYMBOL='venv:'

SPACESHIP_RUBY_PREFIX=' '
SPACESHIP_RUBY_SUFFIX=''
SPACESHIP_RUBY_COLOR='red'
SPACESHIP_RUBY_SYMBOL='Ruby '

SPACESHIP_NODE_PREFIX=' '
SPACESHIP_NODE_SUFFIX=''
SPACESHIP_NODE_COLOR='#b6ffa8'
SPACESHIP_NODE_SYMBOL='Node '

SPACESHIP_VI_MODE_COLOR='white'
SPACESHIP_VI_MODE_INSERT='[I]'
SPACESHIP_VI_MODE_NORMAL='[N]'

SPACESHIP_CHAR_PREFIX=''
SPACESHIP_CHAR_SUFFIX=' '
SPACESHIP_CHAR_COLOR_SUCCESS='white'
SPACESHIP_CHAR_COLOR_FAILURE='white'
SPACESHIP_CHAR_SYMBOL='❯'
SPACESHIP_CHAR_COLOR_SECONDARY='white'
SPACESHIP_CHAR_SYMBOL_SECONDARY='↪ '
SPACESHIP_CHAR_SYMBOL_ROOT=''
